config/routes.rb
Rails.application.routes.draw do
  resources :posts do 
    resources :comments
  end
  resources :users do 
    resources :comments
  end
  resources :users do 
    resources :posts
  end
  resources :follows
  get 'users/:id/user_posts', to: 'users#user_posts', as: "custom_user_posts"
  # resources :users
  root "sessions#welcome", as: "welcome"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy" # is this suppose to be delete instead of get?
  get "welcome", to: "sessions#welcome"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :comments
    # follower_follows "names" the Follow join table for accessing through the follower association
    has_many :follower_follows, foreign_key: :followee_id, class_name: "Follow" 
    # source: :follower matches with the belong_to :follower identification in the Follow model 
    has_many :followers, through: :follower_follows, source: :follower

    # followee_follows "names" the Follow join table for accessing through the followee association
    has_many :followee_follows, foreign_key: :follower_id, class_name: "Follow"    
    # source: :followee matches with the belong_to :followee identification in the Follow model   
    has_many :followees, through: :followee_follows, source: :followee


    validates :username, presence: true, uniqueness: true
    validates :password, presence: true
    # validates :password_confirmation, confirmation: true
    validates :age, numericality: true


    has_secure_password

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :destroy, :index]
  def index
    @users= User.all.order("created_at DESC")
  end

  def new
    @user= User.new
  end
  
  def create
    @user= User.new(user_params)
    # password =
    # byebug
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end
  
  
  def show
    @user = User.find(params[:id])
    @follow = Follow.new
    # byebug
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to @user
      else
        render 'edit'
    end
  end

  def user_posts
    # byebug
    @user = User.find(params[:id])
  end

    

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to @user
  end


  private

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation , :age, :gender)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div>
  <%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br>

    <%= f.label :username %>
    <%= f.text_field :username %> <br>

    <%= f.label :password %>
    <%= f.password_field :password %> <br>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.label :age %>
    <%= f.number_field :age %>

    <%= f.label :gender %>
    <%= f.select :gender, ["Male", "Female", "Other"] %>

    <%= f.submit class:"btn btn-primary" %>
  <% end %>
</div>

<br>
    <strong><% if @user.errors.full_messages.any? %>
  <% @user.errors.full_messages.each do |error_message| %>
    <div style="color:red"> <%= error_message %>! </div> 
  <% end %>
<% end %><strong>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>
<%= render "form" %>

app/views/users/index.html.erb
<div style="text-align:center">
  <h1>List of User Accounts</h1>

  <% @users.each do |u| %>
    <%= link_to u.username.capitalize, u %> <br>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Sign-up Page</h1>
<%= render "form" %>

app/views/users/show.html.erb
<div style="text-align:center">
  <h1>Profile Page</h1>
  <h3>Username: <%= @user.username.capitalize %>  </h3>
  <h3>Age: <%= @user.age %>  </h3>
  <h3>Gender: <%= @user.gender %>  </h3>

  <p>
    Created <%= time_ago_in_words(@user.created_at, include_seconds: true) %> ago
  </p>

  <%= button_to "#{@user.username.capitalize}'s Posts", custom_user_posts_path, :method => :get, class:"btn btn-info" %>

  <% if current_user == @user %>
    <br>
    <%= button_to "logout", logout_path, :method => :delete, class: "btn btn-warning" %>
    <br>
    <!--
    <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-primary"  %>
    -->
    <%= button_to 'Edit Profile', edit_user_path(@user), :method => :get, class: "btn btn-primary"  %>
    <br>

    <%= button_to "delete", @user, :method => :delete, class: "btn btn-danger" %>
    <br>
  <% end %>

  <h3>Follow Users</h3>
<%#= form_tag(follows_path, method: "post") do %>
<%= form_for(@follow) do |f| %>
  <%= f.collection_select :followee_id, User.all, :id, :username %>
  <%= f.submit("Follow")%>
<%end%>

<h3>Your Follows</h3>
<% @user.followees.each do |f| %>
  <%= f.username.capitalize %>,
<% end %>

</div>

app/views/users/user_posts.html.erb
<h1><%=@user.username.capitalize%>'s Posts:</h1>


<% @user.posts.each do |p| %>
  <ul>
  <li><%= link_to p.name, p %> </li>
  </ul> 
<% end %>
<strong> Click here to view <%= link_to @user.username.capitalize, "/users/#{@user.id}"%>'s Profile</strong>